# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180130_2041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0030_auto_20180126_0903'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(default=None, max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Corporative Email')),
                ('closed', models.BooleanField(default=False, help_text='Tells if a deal is closed or open', verbose_name='Closed Deal')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Affiliates')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Services')),
            ],
        ),
        migrations.RemoveField(
            model_name='deals',
            name='prospect',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='service',
        ),
        migrations.DeleteModel(
            name='Deals',
        ),
    ]
