# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20180131_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedeals',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='servicedeals',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Phone Number'),
        ),
    ]
