# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_auto_20180202_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedeals',
            name='buyer_message',
        ),
        migrations.RemoveField(
            model_name='servicedeals',
            name='seller_message',
        ),
        migrations.AddField(
            model_name='servicedeals',
            name='buyer_comment',
            field=models.TextField(blank=True, help_text='Tell us what was your experience with this service?', null=True, verbose_name='Buyer Comment'),
        ),
        migrations.AddField(
            model_name='servicedeals',
            name='seller_comment',
            field=models.TextField(blank=True, help_text='What do you want to say about this client?', null=True, verbose_name='Seller Comment'),
        ),
        migrations.AlterField(
            model_name='servicedeals',
            name='buy_is_finished',
            field=models.BooleanField(default=False, help_text='Did you buy this service ?', verbose_name='Buyer tells deal is finished'),
        ),
        migrations.AlterField(
            model_name='servicedeals',
            name='buyer_is_contacted',
            field=models.BooleanField(default=False, help_text='Did the company make contact with you ?', verbose_name='Buyer tells has been contated'),
        ),
        migrations.AlterField(
            model_name='servicedeals',
            name='sell_is_finished',
            field=models.BooleanField(default=False, help_text='Did you sell this service ?', verbose_name='Seller tells deal is finished'),
        ),
        migrations.AlterField(
            model_name='servicedeals',
            name='seller_has_contacted',
            field=models.BooleanField(default=False, help_text='Have you already made contact with this client ?', verbose_name='Seller tells has contacted buyer'),
        ),
    ]
