# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 16:25
from __future__ import unicode_literals

import companies.validators
from django.db import migrations, models
import django.db.models.deletion
import services.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0030_auto_20180126_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(editable=False, null=True, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(null=True, verbose_name='modification date and time')),
                ('meta_keywords', models.CharField(blank=True, help_text='Separate keywords by comma.', max_length=255, verbose_name='SEO Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='SEO Description')),
                ('meta_author', models.CharField(blank=True, max_length=255, verbose_name='SEO Author')),
                ('meta_copyright', models.CharField(blank=True, max_length=255, verbose_name='SEO Copyright')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Title')),
                ('serv_desc_es', tinymce.models.HTMLField(blank=True, null=True, verbose_name='English Service Description')),
                ('serv_desc_en', tinymce.models.HTMLField(verbose_name='Spanish Service Description')),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('finance', 'Finance'), ('development', 'Development'), ('vacations', 'Vacations'), ('design', 'Design'), ('information_security', 'Information Security')], max_length=25)),
                ('serv_image', models.ImageField(blank=True, null=True, upload_to=services.models.upload_to, validators=[companies.validators.file_size], verbose_name='Service Image')),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Price')),
                ('old_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Price Before')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Discount')),
                ('prospects', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Interested People')),
                ('client', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Satisfied Clients')),
                ('days_left', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Days left')),
                ('is_active', models.BooleanField(default=True, help_text='This tells if a services is published or not', verbose_name='Active ')),
                ('auto_trans', models.BooleanField(default=False, help_text='Create automatic translation of description. You can edit it later in update page', verbose_name='Automatic Translation')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('offerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Affiliates')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
