# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180130_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='en_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
