# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_en_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='en_slug',
            new_name='slug_en',
        ),
    ]
