# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180130_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='en_name',
            field=models.CharField(default=None, max_length=50, verbose_name='English Title'),
        ),
    ]
