# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 19:12
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20180204_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='serv_desc_en',
            field=tinymce.models.HTMLField(verbose_name='English Service Description'),
        ),
        migrations.AlterField(
            model_name='services',
            name='serv_desc_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Spanish Service Description'),
        ),
    ]
