# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Name')),
                ('category', models.CharField(choices=[('mk', 'Marketing'), ('fn', 'Finance'), ('dv', 'Development'), ('vc', 'Vacations'), ('dg', 'Design'), ('is', 'Information Security')], max_length=2)),
                ('years', models.IntegerField(blank=True, verbose_name='Years of fundation')),
                ('conversions', models.IntegerField(blank=True, null=True, verbose_name='Conversions')),
                ('contracts', models.IntegerField(verbose_name='Terminated contracts')),
                ('description_en', models.TextField(verbose_name='English Description')),
                ('description_es', models.TextField(verbose_name='Spanish Description')),
                ('mission', models.TextField(verbose_name='Mission')),
                ('vision', models.TextField(verbose_name='Vision')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prospects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prospects', to=settings.AUTH_USER_MODEL, verbose_name='Prospects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
