# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 21:27
from __future__ import unicode_literals

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliates',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=companies.models.upload_to),
        ),
    ]
