# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_afiliates_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliates',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='afiliates',
            name='prospects',
        ),
        migrations.AddField(
            model_name='afiliates',
            name='prospects',
            field=models.ManyToManyField(related_name='Prospects', to=settings.AUTH_USER_MODEL, verbose_name='Prospects'),
        ),
    ]
