# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20171230_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliates',
            name='contracts',
            field=models.IntegerField(blank=True, null=True, verbose_name='Terminated contracts'),
        ),
    ]
