# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20171230_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliates',
            name='meta_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='afiliates',
            name='meta_copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='afiliates',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='afiliates',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate keywords by comma.', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='afiliates',
            name='prospects',
            field=models.ManyToManyField(related_name='prospects_of', to=settings.AUTH_USER_MODEL, verbose_name='Prospects'),
        ),
    ]
