# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20180101_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliates',
            name='contracts',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Terminated contracts'),
        ),
        migrations.AlterField(
            model_name='afiliates',
            name='conversions',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Conversions'),
        ),
        migrations.AlterField(
            model_name='afiliates',
            name='years',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Years of fundation'),
        ),
    ]
