# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20180101_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliates',
            name='prospects',
            field=models.ManyToManyField(related_name='prospects_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
