# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20180101_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliates',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
