# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20180101_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliates',
            name='name',
            field=models.CharField(default=None, max_length=35, verbose_name='Name'),
        ),
    ]
