# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20180102_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Afiliates',
            new_name='Affiliates',
        ),
    ]
