# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20180112_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliates',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Corporative Email'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='meta_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Author'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='meta_copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Copyright'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate keywords by comma.', max_length=255, verbose_name='SEO Keywords'),
        ),
    ]
