# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20180112_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
    ]
