# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20180112_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Years of fundation'),
        ),
    ]
