# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20180112_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
