# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 07:03
from __future__ import unicode_literals

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_affiliates_lead_magnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='lead_magnet',
            field=models.FileField(blank=True, null=True, upload_to=companies.models.upload_file_to, verbose_name='Lead Magnet'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=companies.models.upload_to, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='modified',
            field=models.DateTimeField(null=True, verbose_name='modification date and time'),
        ),
    ]
