# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_auto_20180113_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modification date and time'),
        ),
    ]
