# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20180113_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='modified',
            field=models.DateTimeField(null=True, verbose_name='modification date and time'),
        ),
    ]
