# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 10:21
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_auto_20180115_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliates',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
