# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_auto_20180119_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='category',
            field=models.CharField(max_length=2),
        ),
    ]
