# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20180119_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='category',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('finance', 'Finance'), ('development', 'Development'), ('vacations', 'Vacations'), ('design', 'Design'), ('information_security', 'Information Security')], max_length=25),
        ),
    ]
