# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 01:08
from __future__ import unicode_literals

import companies.models
import companies.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_auto_20180119_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='English Description'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='lead_magnet',
            field=models.FileField(blank=True, null=True, upload_to=companies.models.upload_file_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png'])], verbose_name='Lead Magnet'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=companies.models.upload_to, validators=[companies.validators.file_size], verbose_name='Logo'),
        ),
    ]
