# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 13:03
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_affiliates_auto_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='English Description'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='description_es',
            field=tinymce.models.HTMLField(verbose_name='Spanish Description'),
        ),
    ]
